language: objective-c
install: true
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods --no-ri --no-rdoc
script:
  - cd Project && pod install
  - cp Classes/BDKAutomaticSecrets.plist.example Classes/BDKAutomaticSecrets.plist
  - xctool -workspace BDKAutomatic.xcworkspace -scheme BDKAutomatic -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build
