language: objective-c
install: true
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods --no-ri --no-rdoc
script:
  - cd Project && pod install
  - xctool -workspace ./Project/BDKAutomatic.xcworkspace -scheme BDKAutomatic -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build
